#ECE 30862 JAVA project

run: Alien.class Barrier.class Bullet_Alien.class BufferedImageLoader.class Bullet.class Controller.class Defender.class EntityA.class EntityB.class Game.class GameObject.class KeyInput.class Logic.class Menu.class

Alien.class: Alien.java
	javac -g Alien.java

Barrier.class: Barrier.java
	javac -g Barrier.java

Bullet_Alien.class: Bullet_Alien.java
	javac -g Bullet_Alien.java

BufferedImageLoader.class: BufferedImageLoader.java
	javac -g BufferedImageLoader.java

Bullet.class: Bullet.java
	javac -g Bullet.java

Controller.class: Controller.java
	javac -g Controller.java

Defender.class: Defender.java
	javac -g Defender.java

EntityA.class: EntityA.java
	javac -g EntityA.java

EntityB.class: EntityB.java
	javac -g EntityB.java

Game.class: Game.java
	javac -g Game.java

GameObject.class: GameObject.java
	javac -g GameObject.java

KeyInput.class: KeyInput.java
	javac -g KeyInput.java

Logic.class: Logic.java
	javac -g Logic.java

Menu.class: Menu.java
	javac -g Menu.java

clean:
	rm -f *.class